---
- name: Configure Kibana on a new host.
  hosts:  "{{ override_hosts | default('all') }}"
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true

  roles:
    #- { role: /home/aniteshl/ansible/wazuh-ansible/roles/wazuh/ansible-kibana, elasticsearch_network_host: 'your elasticsearch IP' }
    - { role: /home/aniteshl/ansible/wazuh-ansible/roles/wazuh/ansible-kibana, elasticsearch_network_host: '10.160.88.198' }
