---
- name: Configure Wazuh Agent on a new host.
  hosts:  "{{ override_hosts | default('all') }}"
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true

  roles:
    - /home/aniteshl/ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-agent

  vars:
    wazuh_managers:
      - address: 10.160.88.150
        port: 1514
        protocol: udp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
    wazuh_agent_authd:
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'

...
