---
- name: Update Oracle Client in TIBCO Machines.
  hosts: "{{ override_hosts | default('TIBCO') }}"
  #hosts: 127.0.0.1
  #connection: local
  user: aniteshl 
  become_user: root
  become_method: sudo
  become: true

  environment:
    PATH: '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'

  vars:
    basedir: '/home/aniteshl/ansible/upgrade_oracle_client'
    files: '{{basedir}}/files' 
    stage_dir: '/opt/oracle/stage'
   # stage_dir: '/tmp/stage'
    response_file: '{{files}}/custom_client.rsp'

  tasks: 
    - name: Creating the stage directory "{{ stage_dir }}"
      file:
        path: "{{ stage_dir }}"
        state: directory
        owner: oracle 
        group: oinstall
        mode: 0755
        recurse: yes
      become: true
      tags: create_stage_dir

    - name: Unarchive the software way to "{{ stage_dir }}". 
      unarchive:
        src: '{{files}}/linuxx64_12201_client.zip' 
        dest: '{{stage_dir}}'  
      become: true
      tags: unarchive_software

    - name: Setting up reponse file for silent installation. 
      copy: 
        src: '{{response_file}}'
        dest: "{{stage_dir}}" 
      become: true
      become_user: oracle
      tags: set_up_response_file  

    - name: Update ownership on "{{ stage_dir }}"
      file:
        dest: "{{ stage_dir }}"
        owner: oracle 
        group: oinstall
        recurse: yes
      become: true
      tags: update_oracle_ownership

    - name: Run the installer in silent mode. 
      command: "'{{stage_dir}}/client/runInstaller' -ignoreSysPrereqs -ignorePrereq -waitforcompletion -showProgress -silent -responseFile '{{stage_dir}}/custom_client.rsp'" 
      args: 
        chdir: '{{stage_dir}}/' 
      become: true
      become_user: oracle
      tags: install_silent_mode

      # This is upon request by the application team and confirmation by the DBAS. 
    - name: Update ownership on /opt/oracle.
      file:
        dest: /opt/oracle 
        owner: tibco 
        group: oinstall
        recurse: yes
      become: true
      tags: update_tibco_ownership

    - name: Deleting the "{{ stage_dir }}"
      file: 
        path:  "{{ stage_dir }}"
        state: absent
      become: true
      tags: delete_stage_dir
...
