---
- block:

  - name: Identify the oldest kernel.
    shell: "rpm -q kernel | head -1"
    register: oldest_kernel

  - debug:
      msg: Oldest kernel is "{{ oldest_kernel.stdout_lines }}"

  - name: Identify the latest kernel.
    shell: "uname -r"
    register: latest_kernel

  - debug:
      msg: Latest kernel is "kernel-{{ latest_kernel.stdout_lines }}"

  - name: Remove oldest kernel.
    yum:
      name: "{{ oldest_kernel.stdout_lines }}"
      state: absent
    when: oldest_kernel.stdout_lines != 'kernel-latest_kernel.stdout_lines'
    ignore_errors: true
...
