---
- block:

  - name: Identify the oldest kernel-tools.
    shell: "rpm -q kernel-tools | head -1"
    register: oldest_kernel_tools

  - debug:
      msg: Oldest kernel is "{{ oldest_kernel_tools.stdout_lines }}"

  - name: Identify the latest kernel-tools.
    shell: "uname -r"
    register: latest_kernel_tools

  - debug:
      msg: Latest kernel is "kernel-{{ latest_kernel_tools.stdout_lines }}"

  - name: Remove oldest kernel-tools.
    yum:
      name: "{{ oldest_kernel_tools.stdout_lines }}"
      state: absent
    when: oldest_kernel_tools.stdout_lines != 'kernel-latest_kernel_tools.stdout_lines'
...
