---
- block:

  - name: Identify the oldest kernel-devel.
    shell: "rpm -q kernel-devel | head -1"
    register: oldest_kernel_devel

  - debug:
      msg: Oldest kernel is "{{ oldest_kernel_devel.stdout_lines }}"

  - name: Identify the latest kernel-devel.
    shell: "uname -r"
    register: latest_kernel_devel

  - debug:
      msg: Latest kernel is "kernel-{{ latest_kernel_devel.stdout_lines }}"

  - name: Remove oldest kernel-devel.
    yum:
      name: "{{ oldest_kernel_devel.stdout_lines }}"
      state: absent
    when: oldest_kernel_devel.stdout_lines != 'kernel-latest_kernel_devel.stdout_lines'
...
