---
yum_packages: 
  - compat-libstdc++
  - elfutils-libelf-devel
  - gcc-c++ libaio-devel
  - libstdc++-devel
  - pdksh
  - compat-libstdc++-33
  - gtk2
  - libXtst
  - libcap
  - ksh
  - compat-libcap1.*
  - compat-libcap2.*
  - libcap*
  - glibc.i686
  - libXp
  - binutils.i386
  - binutils.x86_64
  - libawt
  - libawt.so
  - binutils
  - compat-db
  - compat-gcc-34
  - java
  - java-*
  - compat-gcc-34-c++
  - compat-libstdc++-33
  - compat-libstdc++-33-*
  - compat-libstdc++-296
  - gcc
  - gcc-c++
  - glibc
  - glibc-common
  - glibc-devel
  - glibc-headers
  - libgcc
  - libXp
  - libXt
  - libXtst
  - libaio
  - libaio-devel
  - libgcc
  - libstdc++
  - libstdc++-devel
  - libgomp
  - make
  - numactl-devel
  - sysstat
  - libaio
  - libaio.i686
  - libXp.i686
  - apr
  - apr-util
  - apr-util-ldap
  - glibc-devel.i686
  - libX11.i686
  - libXau.i686
  - libXi.i686
  - libXt.i686
  - libXp.i686
  - libxcb.i686
  - libXtst.i686 
