---
- name: Load EIS user(s) information.
  include_vars: vars/users_eis_admins.yml

- name: Add EIS admins to the new host.
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    comment: "{{ item.comment | default('') }}"
    #group: "{{ item.group | default(item.name) }}"
    group: "{{ item.group | default('usa') }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    append: "{{ item.append | default(false) }}"
    password: "{{ item.password | default('$6$eW52tTL6VnzSNXqb$sUPoq54ioMxZKkAT1HZKNxfZCRrtq8yVQbwEE1YITEP8ZdutUZXbId4fa7hNC15L3vnuyrUXdvD3SjJ4EUBGk.') }}"
    #password: "{{ 'abcd4321' | password_hash('sha512') }}"
    #password: "{{ user_password | password_hash('sha512') }}"
    update_password: "{{ item.update_password | default('always') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
    system: "{{ item.system | default(false) }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default(false) }}"
  with_items: "{{ users_eis_admins }}"
  ignore_errors: true
  tags:
    - add_users_eis_admins

- name: Update ownership and permissions for EIS Admins.
  file:
    path: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode:
    state: directory
  when: item.state | default('present') == 'present' and item.dir_mode is defined
  with_items: "{{ users_eis_admins }}"
  tags:
    - update_mode_ownership_for_eis_admins
...
