galaxy_info:
  author: Asa Gage
  description: Provides a module to manage/unmanage nodes in Solarwinds Orion
  license: MIT

  min_ansible_version: 2.5

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - solarwinds
    - orion
    - swis

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.