---
- name: Applying base Red Hat Satellite Conditions.  
  include_tasks: "rhel-sat-config.yml"
  when: (ansible_os_family == "RedHat")

- name: Applying Red Hat 6 Satellite configuration. 
  include_tasks: "rhel-6-sat-config.yml"
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")

- name: Applying Red Hat 6 Satellite configuration.
  include_tasks: "rhel-7-sat-config.yml"
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")

#- name: Finalizing Red Hat configuration
#  include_tasks: "rhel-final-config.yml"
#  when: (ansible_os_family == "RedHat")
    
...
